Repository Final-Capstone-Elite-Group/RentUrTechBackend, pull requests merged in 2022-06, with the labels that each got.

#17 Set Up Rails Application
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/linters.yml
  .gitignore
  .rspec
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  spec/rails_helper.rb
  spec/spec_helper.rb
  storage/.keep
  tmp/.keep
  tmp/pids/.keep
  tmp/storage/.keep
  vendor/.keep
Labels: enhancement

#22 Feature/equipment reservation resource
  app/models/equipment.rb
  app/models/equipment_reservation.rb
  app/models/reservation.rb
  app/models/user.rb
  db/migrate/20220602162050_create_reservations.rb
  db/migrate/20220603030545_create_equipment_reservations.rb
  db/migrate/20220603032604_add_user_ref_to_reservations.rb
  db/schema.rb
  spec/factories/equipment_reservations.rb
  spec/factories/reservations.rb
  spec/models/equipment_reservation_spec.rb
Labels: enhancement

#25 Add bad request responses and fix sign up bug
  .byebug_history
  app/controllers/auth/authenticate_user.rb
  app/controllers/authentication_controller.rb
  app/controllers/users_controller.rb
  app/interactors/users/create.rb
Labels: bug

#20 Define Equipment Create Action
  .byebug_history
  .github/PULL_REQUEST_TEMPLATE.md
  Gemfile
  Gemfile.lock
  app/controllers/equipments_controller.rb
  app/interactors/equipments/create.rb
  app/models/equipment.rb
  app/serializers/serializable_equipment.rb
  config/environments/development.rb
  config/environments/test.rb
  db/seeds.rb
  spec/assets/test.png
  spec/controllers/equipments_controller_spec.rb
  spec/factories/equipments.rb
  spec/models/equipment_spec.rb
Labels: enhancement

#28 Define Equipment show action
  .gitignore
  app/controllers/equipments_controller.rb
  app/interactors/equipments/index.rb
  app/interactors/equipments/show.rb
  app/models/equipment.rb
  app/models/user.rb
  spec/controllers/equipments_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: enhancement, testing

#30 Add Index Reservations action
  .byebug_history
  app/controllers/reservations_controller.rb
  app/interactors/reservations/index.rb
  app/models/reservation.rb
  app/serializers/serializable_reservation.rb
  config/initializers/cors.rb
  spec/controllers/reservations_controller_spec.rb
  spec/models/reservation_spec.rb
  storage/ee/bi/eebizg6lvlofek900s5xhigk31in
  storage/kz/of/kzofo0ymjfkj6n7pdgs81jvn9s6o
Labels: enhancement, testing

#31 Bugfix/time complexity
  .gitignore
  app/controllers/auth/authenticate_user.rb
  app/controllers/users_controller.rb
  app/interactors/reservations/create.rb
  app/interactors/reservations/destroy.rb
  app/models/user.rb
  app/serializers/serializable_equipment.rb
  app/serializers/serializable_reservation.rb
  db/seeds.rb
  spec/models/equipment_spec.rb
  storage/ee/bi/eebizg6lvlofek900s5xhigk31in
  storage/kz/of/kzofo0ymjfkj6n7pdgs81jvn9s6o
Labels: bug

#32 Feature/documentation
  .gitignore
  README.md
  postman/schemas/rent_ur_tech_schema.json
Labels: documentation

#34 Feature/amazon image storage
  Gemfile
  Gemfile.lock
  app/models/equipment.rb
  app/models/reservation.rb
  config/credentials.yml.enc
  config/environments/production.rb
  config/storage.yml
  db/seeds.rb
  storage/images/powerfulpc.jpg
Labels: enhancement

#37 Feature/add validations
  app/models/equipment.rb
  spec/factories/equipments.rb
  spec/models/equipment_spec.rb
Labels: enhancement

#39 Feature/deployment
  Gemfile
  config/credentials/production.yml.enc
  config/credentials/test.key
  config/credentials/test.yml.enc
  config/environments/production.rb
  lib/json_web_token.rb
Labels: enhancement

#43 Add cors permition to netlify host
  config/initializers/cors.rb
Labels: bug
